# Generated by Django 2.2.6 on 2019-11-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikecircle', '0002_auto_20191031_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
