# Generated by Django 2.2.6 on 2019-11-10 03:10

from django.db import migrations

def init_passcode(apps, schema_editor):
    Passcode = apps.get_model('strikecircle', 'Passcode')
    initial_passcode = Passcode(passcode='sunrise', active=True)
    initial_passcode.save()

class Migration(migrations.Migration):

    dependencies = [
        ('strikecircle', '0003_passcode'),
    ]

    operations = [
        migrations.RunPython(init_passcode)
    ]
