# Generated by Django 2.2.8 on 2020-01-13 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strikecircle', '0006_pledge_strike_circle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strikecircle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
