# Generated by Django 2.2.9 on 2020-01-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikecircle', '0008_auto_20200114_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='one_on_one',
            field=models.DateField(blank=True, null=True),
        ),
    ]
