# Generated by Django 2.2.6 on 2019-10-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledgetovote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
