# Generated by Django 2.2.8 on 2020-01-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pledgetovote', '0005_auto_20200112_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='strike_circle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pledgetovote.StrikeCircle'),
            preserve_default=False,
        ),
    ]
